CREATE SCHEMA IF NOT EXISTS rrhh;
SET search_path TO rrhh;

CREATE TABLE IF NOT EXISTS roles_app (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS roles_operativos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  aparece_plan_semanal INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS personas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  codigo_privado TEXT UNIQUE,
  email TEXT,
  rol_operativo_id INTEGER REFERENCES roles_operativos(id),
  activo INTEGER NOT NULL DEFAULT 1,
  horario_tipo TEXT NOT NULL DEFAULT 'variable',
  horario_fijo_json TEXT,
  valor_hora DOUBLE PRECISION NOT NULL DEFAULT 0,
  horas_acordadas DOUBLE PRECISION NOT NULL DEFAULT 190,
  tipo_libreta TEXT NOT NULL DEFAULT 'NO TIENE',
  vencimiento_libreta TEXT,
  vencimiento_carne_salud TEXT
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email TEXT,
  persona_id INTEGER REFERENCES personas(id),
  rol_app_id INTEGER NOT NULL REFERENCES roles_app(id),
  activo INTEGER NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_persona_unique
ON usuarios(persona_id)
WHERE persona_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS turnos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INTEGER NOT NULL REFERENCES personas(id),
  fecha TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'VACIO',
  hora_inicio TEXT,
  hora_fin TEXT,
  actividad_ubicacion TEXT,
  modificado INTEGER NOT NULL DEFAULT 0,
  origen TEXT NOT NULL DEFAULT 'PLAN',
  origen_referencia_tipo TEXT,
  origen_referencia_id INTEGER,
  fecha_regularizacion TEXT,
  UNIQUE (persona_id, fecha)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_turnos_persona_fecha_unique
ON turnos(persona_id, fecha);

CREATE TABLE IF NOT EXISTS marcas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INTEGER NOT NULL REFERENCES personas(id),
  fecha_hora TEXT NOT NULL,
  tipo TEXT NOT NULL,
  tipo_marca TEXT NOT NULL,
  actividad_ubicacion TEXT,
  ubicacion_detectada TEXT,
  latitud DOUBLE PRECISION,
  longitud DOUBLE PRECISION,
  genera_incidencia INTEGER NOT NULL DEFAULT 0,
  estado_aprobacion TEXT NOT NULL DEFAULT 'PENDIENTE',
  fecha_aprobacion TEXT,
  aprobado_por_usuario_id INTEGER REFERENCES usuarios(id),
  observacion_aprobacion TEXT,
  fecha_modificacion TEXT,
  modificado_por_usuario_id INTEGER REFERENCES usuarios(id),
  observacion_modificacion TEXT,
  anulada INTEGER NOT NULL DEFAULT 0,
  fecha_anulacion TEXT,
  anulada_por_usuario_id INTEGER REFERENCES usuarios(id),
  observacion_anulacion TEXT
);

CREATE TABLE IF NOT EXISTS operacion_tarifas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria TEXT NOT NULL,
  tipo TEXT NOT NULL,
  hasta_4hs DOUBLE PRECISION NOT NULL DEFAULT 0,
  de_4_a_8hs DOUBLE PRECISION NOT NULL DEFAULT 0,
  de_8_a_12hs DOUBLE PRECISION NOT NULL DEFAULT 0,
  activo INTEGER NOT NULL DEFAULT 1,
  fecha_creacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  fecha_actualizacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE INDEX IF NOT EXISTS idx_operacion_tarifas_activo
ON operacion_tarifas(activo);

CREATE TABLE IF NOT EXISTS persona_operacion_tarifas (
  persona_id INTEGER NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  tarifa_id INTEGER NOT NULL REFERENCES operacion_tarifas(id) ON DELETE CASCADE,
  PRIMARY KEY (persona_id, tarifa_id)
);

CREATE INDEX IF NOT EXISTS idx_persona_operacion_tarifas_persona
ON persona_operacion_tarifas(persona_id);

CREATE TABLE IF NOT EXISTS operaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INTEGER NOT NULL REFERENCES personas(id),
  operacion_tarifa_id INTEGER REFERENCES operacion_tarifas(id),
  fecha_hora TEXT NOT NULL,
  tipo_operacion TEXT NOT NULL,
  franja TEXT NOT NULL,
  valor DOUBLE PRECISION NOT NULL DEFAULT 0,
  referencia TEXT,
  observacion TEXT,
  estado TEXT NOT NULL DEFAULT 'pending',
  motivo_rechazo TEXT
);

CREATE TABLE IF NOT EXISTS facturacion (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden TEXT NOT NULL,
  fecha TEXT NOT NULL,
  monto DOUBLE PRECISION NOT NULL DEFAULT 0,
  referencia TEXT,
  lugar TEXT,
  observacion TEXT,
  fecha_creacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  fecha_actualizacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE INDEX IF NOT EXISTS idx_facturacion_fecha
ON facturacion(fecha);

CREATE TABLE IF NOT EXISTS ubicaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  google_maps_url TEXT,
  latitud DOUBLE PRECISION,
  longitud DOUBLE PRECISION,
  tolerancia_metros INTEGER NOT NULL DEFAULT 500,
  genera_incidencia INTEGER NOT NULL DEFAULT 0,
  direccion TEXT
);

CREATE TABLE IF NOT EXISTS incidencias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave TEXT UNIQUE,
  persona_id INTEGER REFERENCES personas(id),
  fecha TEXT NOT NULL,
  tipo TEXT NOT NULL,
  severidad TEXT NOT NULL DEFAULT 'INFO',
  detalle TEXT,
  origen TEXT NOT NULL DEFAULT 'SISTEMA',
  referencia_tipo TEXT,
  referencia_id INTEGER,
  minutos_desfasaje INTEGER,
  resuelta INTEGER NOT NULL DEFAULT 0,
  fecha_resolucion TEXT,
  aprobado_por_usuario_id INTEGER REFERENCES usuarios(id),
  observacion_aprobacion TEXT,
  fecha_creacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  fecha_actualizacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_incidencias_clave_unique
ON incidencias(clave);

CREATE TABLE IF NOT EXISTS jornales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id INTEGER NOT NULL REFERENCES personas(id),
  fecha TEXT NOT NULL,
  turno_id INTEGER REFERENCES turnos(id),
  entrada_marca_id INTEGER REFERENCES marcas(id),
  salida_marca_id INTEGER REFERENCES marcas(id),
  estado_turno TEXT NOT NULL DEFAULT 'VACIO',
  hora_inicio_plan TEXT,
  hora_fin_plan TEXT,
  actividad_ubicacion TEXT,
  entrada_hora TEXT,
  salida_hora TEXT,
  estado_aprobacion TEXT NOT NULL DEFAULT 'PENDIENTE',
  modo_aprobacion TEXT,
  aprobado_por_usuario_id INTEGER REFERENCES usuarios(id),
  aprobado_por TEXT,
  fecha_aprobacion TEXT,
  observacion_aprobacion TEXT,
  horas_previstas DOUBLE PRECISION NOT NULL DEFAULT 0,
  horas_trabajadas DOUBLE PRECISION NOT NULL DEFAULT 0,
  fecha_actualizacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  UNIQUE (persona_id, fecha)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_jornales_persona_fecha_unique
ON jornales(persona_id, fecha);

CREATE TABLE IF NOT EXISTS configuracion (
  clave TEXT PRIMARY KEY,
  valor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sesiones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  fecha_creacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  fecha_expiracion TEXT NOT NULL,
  activa INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_sesiones_token_hash
ON sesiones(token_hash);

CREATE INDEX IF NOT EXISTS idx_sesiones_usuario
ON sesiones(usuario_id);
